### ISSUE TITLE
请问本地调试的时候,cookie是如何读取呢?

### ISSUE THREAD

**Issue by xjdata** [tkvern/dva-passport#1]
谢谢你开源的项目.让我学习到了很多知识.

有点环境方面的问题,想请教你下,请指导. 谢谢.

我的项目环境与你相似,不同的是后端采用了yii2,前端也是antd.

请问,在开发环境下,前端登录后 php发送的setcookie的结果是否可以读取? 

开发时前端地址是localhost:8989, 这个时候登录成功后 读取不到cookie.

我没有模拟线上环境. 但是开发的时候这个cookie读取不到, 不好确定这部分是否没问题.

不知道我描述的是否能够方便你理解.  自己也尝试调试了下, 但是因为开发环境是localhost, 但是后端发送的cookie,domain=xxx.xxx.xxxx  是不是因为这个原因呢?   但是我自己尝试将后端domain修改为localhost 但是getcookie还是无法读取cookie. 没办法了只好来问你. 谢谢.

**Comment by tkvern** [comment]
其实是这样的，假设php后端登录的Domain 是 `login.example.com`。
登录成功后，set-Cookie的Domain是 `*.example.com` （或 `.example.com`）。
ant的项目在`$ npm run start` 后的默认地址为`http://localhost:8989` 或 `http://127.0.0.1:8989`。

这时候的问题就是`localhost`这个域下面访问不到`.example.com`域下面的Cookie。
解决方案1:
修改hosts，添加下面内容到末尾。`test.example.com`在`*.example.com`的范围内，这样就可以取到对应的Cookie了。
```
127.0.0.1  test.example.com
```

解决方案2:
Chrome浏览器安装`Host Switch Plus`插件，同上配置虚拟Hosts，同时对应上端口号，如果dora有端口冲突，则修改dora的端口号即可

**Comment by xjdata** [comment]
太感谢了. 谢谢你!

**Comment by xcgs123** [comment]
> 其实是这样的，假设php后端登录的Domain 是 `login.example.com`。
> 登录成功后，set-Cookie的Domain是 `*.example.com` （或 `.example.com`）。
> ant的项目在`$ npm run start` 后的默认地址为`http://localhost:8989` 或 `http://127.0.0.1:8989`。
> 
> 这时候的问题就是`localhost`这个域下面访问不到`.example.com`域下面的Cookie。
> 解决方案1:
> 修改hosts，添加下面内容到末尾。`test.example.com`在`*.example.com`的范围内，这样就可以取到对应的Cookie了。
> 
> ```
> 127.0.0.1  test.example.com
> ```
> 
> 解决方案2:
> Chrome浏览器安装`Host Switch Plus`插件，同上配置虚拟Hosts，同时对应上端口号，如果dora有端口冲突，则修改dora的端口号即可

为什么我2种方法设置都拿不到cookie，还是跳登录页呢
