### ISSUE TITLE
为什么要写cookie？

### ISSUE THREAD

**Issue by ouzhou** [tkvern/dva-passport#2]
看了您的文章让我学到了很多，这里有个疑惑，因为是用的token可以直接存在localstore里面，为什么要存在cookie里面？

**Comment by tkvern** [comment]
[cookie介绍](http://baike.baidu.com/link?url=BraNrZLyj2tyN8IGsD_lB7Xw3kY9giKnBjiOhoNx7H9rZd7xfcpAJo11elLlmxHVGIqWOy2SGbH7MpVxbaLux_)
